name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting live channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LISTENING_7680F }}
          projectId: listening-7680f
          target: listeningpractice
          channelId: live
